# Generated by Django 3.0.5 on 2020-04-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_drive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='rdvdrive',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rdvdrive',
            name='nb_hour',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rdvdrive',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='nb_hour_Paid',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='nb_hour_lesson',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='adress',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='zip_code',
            field=models.CharField(default='43701', max_length=5, null=True),
        ),
    ]
