# Generated by Django 3.0.5 on 2020-04-16 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_drive', '0002_auto_20200415_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='rdvdrive',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='rdvdrive',
            name='city',
        ),
        migrations.RemoveField(
            model_name='rdvdrive',
            name='zip_code',
        ),
        migrations.RemoveField(
            model_name='student',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='student',
            name='city',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='instructor',
            name='instructor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rdvdrive',
            name='place',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
    ]
